ip = "127.0.0.1"
port = "2224"
username = "go"
password = "forever"
pidfile = "goforever.pid"
logfile = "goforever.log"
errfile = "goforever.log"

[[process]]
name = "hello8080"
command = "./example/hello8080"
pidfile = "example/hello8080.pid"
logfile = "example/hello8080.debug.log"
errfile = "example/hello8080.errors.log"
respawn = 10
delay = "1m"
ping = "30s"

[[process]]
name = "hello8081"
command = "./example/hello8081"
pidfile = "example/hello8081.pid"
logfile = "example/hello8081.debug.log"
errfile = "example/hello8081.errors.log"
respawn = 10
delay = "1m"
ping = "30s"

#[[process]]
#name = "example"
#command = "./example/example"
#args = ["-name=foo"]
#pidfile = "example/example.pid"
#logfile = "example/logs/example.debug.log"
#errfile = "example/logs/example.errors.log"
#respawn = 1
